@BaseAddress = http://localhost:5055

GET {{BaseAddress}}/api/categories
Accept: application/json 
###

Post {{BaseAddress}}/api/categories
Accept: application/json 
Content-Type: application/json 
{
  "name": "test category2"
}
###

GET {{BaseAddress}}/api/categories/08de8a9f-1c95-d97e-1ece-51af622f0000
Accept: application/json 
###