@BaseAddress = http://localhost:5055
@categoryId = 08defa5c-f3ee-be55-1ece-51af622f0000
@courseId = 08defc6f-92ff-a11f-0015-5dd3501f0000
@userId = 08defa5d-555a-cd4c-1ece-51af622f0000

GET {{BaseAddress}}/api/v1/categories
Accept: application/json 
###

POST {{BaseAddress}}/api/v1/categories
Accept: application/json 
Content-Type: application/json 
{
  "name": "test category3"
}
###

GET {{BaseAddress}}/api/v1/categories/{{categoryId}}
Accept: application/json 
###

POST {{BaseAddress}}/api/v1/courses
Accept: application/json
Content-Type: application/json

{
  "name": "test course8",
  "description": "test description",
  "price": 100,
  "imageUrl": "http://example.com/picture.jpg",
  "categoryId":  "{{categoryId}}"
}
###

PUT {{BaseAddress}}/api/v1/courses
Accept: application/json 
Content-Type: application/json 
{
  "id": "{{courseId}}",
 "name": "test course44",
  "description": "test description",
  "price": 200,
  "imageUrl": "http://example.com/picture2.jpg",
  "categoryId":  "{{categoryId}}"
}
###
 
GET {{BaseAddress}}/api/v1/courses
Accept: application/json 
###

GET {{BaseAddress}}/api/v1/courses/{{courseId}}
Accept: application/json 
###
  
GET {{BaseAddress}}/api/v1/courses/user/{{userId}}
Accept: application/json 
###
  
DELETE {{BaseAddress}}/api/v1/courses/{{courseId}}
Accept: application/json 
###




